apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-site
  template:
    spec:
      containers:
      - name: static-site
        image: prabhakaran7720/nginx:v1
        ports:
        - containerPort: 80

